name: date_image_picker
description: A package to pick and arrange images by date in Flutter!
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  photo_manager: ^2.5.2
  permission_handler: 10.2.0
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1

flutter: